#ifndef CAN_NODE_FAN_CONF_H
#define CAN_NODE_FAN_CONF_H

#define NODE_ID 0x21U
#define NUMBER_OF_CAN_MESSAGE_CONFIGS 2U

/* Message masks */
#define CAN_MESSAGE_FANCONTROL_MASK 0x300000U
#define CAN_MESSAGE_FANCONTROL_INDEX 0U

#define CAN_MESSAGE_FANSTATUS_MASK 0x400000U
#define CAN_MESSAGE_FANSTATUS_INDEX 1U

#endif /* End of CAN_NODE_FAN_CONF_H */
