/*
 * This file is autogenerated by Meddela, any modification done to this file
 * will be lost when the code is regenerated.
 */
#ifndef CAN_NODE_WHEEL_CONF_XMC1400_H
#define CAN_NODE_WHEEL_CONF_XMC1400_H

#include "Dave/Generated/CAN_NODE/can_node.h"

#define CAN_MESSAGE_CONFIGS { \
	(CAN_NODE_LMO_t *) &CAN_NODE_Wheel_LMO_WheelControl_Config, \
	(CAN_NODE_LMO_t *) &CAN_NODE_Wheel_LMO_WheelStatus_Config, \
	NULL, \
	NULL, \
	NULL, \
	NULL, \
	NULL, \
	NULL, \
	NULL, \
	NULL, \
	NULL, \
	NULL, \
	NULL, \
	NULL, \
	NULL, \
	NULL, \
	NULL, \
	NULL, \
	NULL, \
	NULL, \
	NULL, \
	NULL, \
	NULL, \
	NULL, \
	NULL, \
	NULL, \
	NULL, \
	NULL, \
	NULL, \
	NULL, \
	NULL, \
	NULL \
}

/* Message configs */
extern XMC_CAN_MO_t CAN_NODE_Wheel_LMO_WheelControl;
extern const CAN_NODE_LMO_t CAN_NODE_Wheel_LMO_WheelControl_Config;

extern XMC_CAN_MO_t CAN_NODE_Wheel_LMO_WheelStatus;
extern const CAN_NODE_LMO_t CAN_NODE_Wheel_LMO_WheelStatus_Config;


extern void CAN_NODE_0_SendMessage(uint8_t message_index, uint8_t *data);
extern void CAN_NODE_0_ReceiveHandler(void);

#endif /* End of CAN_NODE_WHEEL_CONF_XMC1400_H */
