#ifndef CAN_NODE_WHEEL_CONF_H
#define CAN_NODE_WHEEL_CONF_H

#define NODE_ID 0x11U
#define NUMBER_OF_CAN_MESSAGE_CONFIGS 2U

/* Message masks */
#define CAN_MESSAGE_WHEELCONTROL_MASK 0x100000U
#define CAN_MESSAGE_WHEELCONTROL_INDEX 0U

#define CAN_MESSAGE_WHEELSTATUS_MASK 0x200000U
#define CAN_MESSAGE_WHEELSTATUS_INDEX 1U

#endif /* End of CAN_NODE_WHEEL_CONF_H */
